version: '3'

services:
  
  jenkins:
    image: jenkins/docker
    build: 
      context: .
    container_name: jenkins
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/jenkins_home:/var/jenkins_home'
      - '$HOME/spring-petclinic:/var/jenkins_home/spring-petclinic'
      - '$HOME/.m2:/var/jenkins_home/.m2'
    ports:
      - 8090:8080
    networks:
      - net

  registry:
    image: registry:latest
    container_name: registry
    ports:
      - 5000:5000
    networks:
      - net

networks:
  net:
