pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        echo 'Builing *jar file'
        sh "cd $WORKSPACE && ./jenkins/mvn.sh -B -DskipTests clean package"
      }
    }
    stage('Test') {
        steps {
          echo 'Running tests'
          sh "cd $WORKSPACE && ./jenkins/mvn.sh test"
      }
    }
    stage('Artefact') {
      steps {
        echo 'Builing java image file'
        sh "cd $WORKSPACE && ./jenkins/build/build_image.sh ${JOB_NAME} ${BUILD_NUMBER}"
        sh "cd $WORKSPACE && ./jenkins/artifact/push.sh ${JOB_NAME} ${BUILD_NUMBER}"
      }
    }
  }
}
