pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        echo 'Builing *jar file'
        sh "echo $PWD"
        sh "echo $WORKSPACE"
        sh "./jenkins/mvn.sh -B -DskipTests clean package"
      }
    }
    stage('Test') {
        steps {
          echo 'Running tests'
          sh "./jenkins/mvn.sh test"
      }
    }
    stage('Artefact') {
      steps {
        echo 'Builing java image file'
        sh "./jenkins/build/build_image.sh ${JOB_NAME} ${BUILD_NUMBER}"
        sh "./jenkins/artifact/push.sh ${JOB_NAME} ${BUILD_NUMBER}"
      }
    }
  }
}
